class CustomUtils:
    SUCCESSFUL = 1
    SOMETHING_WENT_WRONG = -1
    WRONG_CREDENTIALS = -2
    CUSTOMER_DOES_NOT_EXIST = -3
    ROOM_NOT_AVAILABLE = -4
    CUSTOMER_NOT_LOGGED_IN = -5
    EMAIL_SENDING_FAILED = -6
    CUSTOMER_WITH_EMAIL_NOT_EXIST = -7


