class CustomUtils:
    SUCCESSFUL = 1
    SOMETHING_WENT_WRONG = -1
    WRONG_CREDENTIALS = -2
    CUSTOMER_DOES_NOT_EXIST = -3
    ROOM_NOT_AVAILABLE = -4
    ROOM_WITH_GIVEN_ID_EXIST = -5
    CUSTOMER_NOT_LOGGED_IN = -6
    EMAIL_SENDING_FAILED = -7
    CUSTOMER_WITH_EMAIL_NOT_EXIST = -8


